### ISSUE TITLE
TextPad 8.5.0 returns "(404) Not Found."

### ISSUE THREAD

**Issue by ericmschmidt** [shiitake/have-some-chocolate#10]
I was trying to install the latest version of the TextPad chocolatey package and apparently they have taken that version down so the installation fails.

![image](https://user-images.githubusercontent.com/8714769/108765865-99ca5500-7511-11eb-8a01-769234654fa7.png)

**Comment by radoslaf85** [comment]
I wish this TEXTPAD was written a bit better. The problem is following URL 'https://www.textpad.com/file?path=v85/x64/txpeng850-64.zip' This version is no longer available on vendor page https://www.textpad.com/download. The fix is simple just change the URL to '851'. If there would be possible to install all available version that would be super nice.

**Comment by shiitake** [comment]
Sorry to keep you waiting @ericmschmidt @radoslaf85 

I've pushed out the update to chocolatey today.  It's pending moderation but you should still be able to install using 

```choco install textpad --version=8.5.1```
